#!/usr/bin/env bash
# This script parses the Apache log file, groups visitors by IP and HTTP status code, and displays the data
# Format: OCCURRENCE_NUMBER IP HTTP_CODE

awk '{key = $1 FS $9; count[$key]++;} END {for (key in count) printf("%d %s\n", count[key], key)}' apache-access.log
